### ISSUE TITLE
snippet for creating sharedExamples

### ISSUE THREAD

**Issue by mbajic** [younata/QuickSnippets#1]
qshare -> `sharedExamples("somestring") { (sharedContext: @escaping (Void) -> [String: Any]) in }`

**Comment by younata** [comment]
Took 3 years, but I just added `qsh`, which expands to

```swift
sharedExamples("<#a shared behavior#>") { (ctx: @escaping () -> [String: Any]) in
    <#Shared tests#>
}
```
